### ISSUE TITLE
comment lines

### ISSUE THREAD

**Issue by BertrandSim** [ssb22/jianpu-ly#10]
Hi Silas,

Is there a way to insert comments in the input file? I searched through the list [here](http://ssb22.user.srcf.net/mwrhome/jianpu-ly.html) but could not find anything about comments.

Bertrand

**Comment by ssb22** [comment]
Hi Bertrand, currently the only way to add comments is either to write them in an `LP:` block:

    LP:
    % This is a comment
    :LP

or to write them as a header that Lilypond doesn't recognise and therefore ignores:

    comment=This is a comment

but neither of these are obvious so, perhaps we should add a `%` comment option as well.

**Comment by BertrandSim** [comment]
Hi Silas, thanks for the reply. 

> either to write them in an `LP:` block
> or to write them as a header
> `comment=This is a comment`

Great, let me work with these.
As for the `%` comment option, that is definitely a welcome feature.  
For simplicity, I think a line beginning with `%` will suffice (ie. a comment on a line of its own)
In the meantime,  I will use the above two approaches that you suggested.

Thanks!
Bertrand
