### ISSUE TITLE
Switching the Slur and Beam position

### ISSUE THREAD

**Issue by alvin-nt** [ssb22/jianpu-ly#12]
Is it possible to modify the script (maybe the output file), so that the position of the slurs and beams are swapped?

- beams at above the numbers
- slurs are at the bottom

**Comment by alvin-nt** [comment]
the jianpus being used at my congregation apparently uses this feature (slurs at the bottom, beams at the top). In addition, it also uses a different notation for sharps and flats (a sharp is denoted as forward slash on the number, while a flat is denoted as a backward slash on the number). being able to generate something that follows such convention would be a nice feature.

For the bars and slurs, I managed to make something decent by editing the following lines

```
\override Stem #'direction = #UP
\override Stem #'X-offset = #0.2
\override Stem #'Y-offset = #1
\override Stem #'length-fraction = #0
```

and I need to add these to every related first bar to make the beams look right.

```
\once \override Tie #'staff-position = #0
```

**Comment by alvin-nt** [comment]
PS: I agree that the format is not technically a jianpu, but just a variant of numbered musical notation. I just found that your script really helps with generating a look-alike 😅

**Comment by ssb22** [comment]
Thanks for telling me it's called "not angka".  Searching Google for this finds many examples from Indonesia.  I think we may be able to add a not-angka mode to the script, although it may take a while to get everything to look right....
