### ISSUE TITLE
Errors running python 3.10

### ISSUE THREAD

**Issue by genus1** [ssb22/jianpu-ly#16]
Below is the file and error with python 3.10 and lilypond 2.22.2 and windows 11
Not sure how you add version for translation.

birth.ji
title=Happy Birthday
1=C
3/4

0 0 q5 q5
6 5 1'
7 - q5 q5
6 5 2'
1' - q5 q5
5' 3' 1'
7 ( 6 ) \fermata q4' q4'
3' 1' 2'
1' - -

Error compiling:
G:\lilypond>python jianpu-ly.py birth.ji > birth.ly
Traceback (most recent call last):
  File "jianpu-ly.py", line 920, in <module>
    if __name__=="__main__": main()
  File "jianpu-ly.py", line 916, in main
    inDat = get_input()
  File "jianpu-ly.py", line 528, in get_input
    inDat=[stdin.read()]
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\codecs.py", line 496, in read
KeyboardInterrupt

**Comment by ssb22** [comment]
Thanks, sorry about this.  It's a regression in version 1.58: when I was refactoring the code so it could be imported (for #15), I accidentally deleted 2 spaces at the start of (what is now) line 528, so the read from standard input became unconditional.  As all my tests used standard input, I didn't notice that the option to set a filename without using `<` (first introduced in v1.148) was no longer working.

Until I upload a fix, please put `<` before the input filename to work around this.
