### ISSUE TITLE
Lyrics to skip the intro

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#21]
When I put the lyrics into my sound, I found that they show up in the intro section -- the leading part that involves only instrument, not songs. 

Any way for the lyrics to skip the intro, and show up under the verse instead please? A sample is very appreciated.

**Comment by ssb22** [comment]
Yes, it's the Lilypond `\skip` command which you can just write into an `L:` line:

    1 2 3 4 5 6 5 - 5 4 3 2 1 - - -
    L: \repeat unfold 7 { \skip 1 } And here are the words.

**Comment by suntong** [comment]
Thanks a lot sir!
