### ISSUE TITLE
Multiple Voices?

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#22]
If multiple voices possible with jianpu-ly?   
I.e., same song sang by different group of people Soprano, Alto, Tenor, Bass etc with their own tunes, and put  on the same sheet.

Again from the afromentend jianpu bible, p3:

> You can use voice name marker such as Soprano, Mezzo-soprano, Alto, Tenor,
Baritone, Bass, Lead, ... Please put them before the system bracket.

**Comment by ssb22** [comment]
Yes, use `NextPart` and `instrument` (the human voice counts as an instrument...)

    instrument=Soprano
    1 2 3 4
    L: lah lah di dah
    NextPart instrument=Alto
    5, 6, 7, 1
    L: dum dum di dum
    NextPart instrument=Tenor
    3, 4, 5, 6,
    L: pom pom pom pom

**Comment by suntong** [comment]
Gocha. Thx!!

**Comment by suntong** [comment]
Oh, a follow up question, what's the syntax to change instrument / voice?

I just dup the above lines again, but got:

`Error: Changing header 'instrument' from 'Tenor' to 'Soprano' (is there a missing NextPart or NextScore?)`

Our music basically have three instruments / voices. The first line keeps changing from `T.B` to `S.A` to `T.S`... and the 2nd and 3rd lines keeps changing like that as well.

**Comment by ssb22** [comment]
Hi, I'm afraid changing instrument or voice in the middle of the *same* part isn't really supported, but you can hack it with Lilypond code:

    instrument=Bass
    1, 2, 3, 4,
    LP: \mark \markup "Change to Soprano" \set Staff.shortInstrumentName = "S"
    :LP
    1' 2' 3' 4'
    L: low low low low high high high high

**Comment by suntong** [comment]
> Maybe just make it an ordinary text command

YEP! 

```
instrument=1
1, ^"T.B." 2, 3, 4,
1' ^"S.A" 2' 3' 4'
L: mlow low mlow low whigh high whigh high

NextPart instrument=2
1, ^"S" - 3, -
1 ^"T" - 3 -

NextPart instrument=3
1 ^"A" - 3 -
1, ^"B" - 3, -
```

That works perfectly!! 

![image](https://user-images.githubusercontent.com/422244/226680376-968abd1e-f688-4043-967a-7ae503a72667.png)


Thanks!!!
