### ISSUE TITLE
[Feature Request] go up/down by one octave

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#24]
Again borrowing from https://alda.io/tutorial/

> An interesting thing to note here is the >. This is Alda syntax for “go up to the next octave.” An octave, in scientific pitch notation, starts on a C and goes up to a B. Once you go above that B, the notes start over from C and you are in a new octave. In Alda, each instrument starts in octave 4, and remains in that octave until you tell it to change octaves. You can do that in one of two ways: you can use < and > to go down or up by one octave; or, you can jump to a specific octave using o followed by a number. 

I believe that jianpu-ly notation currently support (only) the second method from above, and if we introduce the first method of “going up/down to the next octave” syntax, using > and <, it can simplify music scripting in normal cases. 

It's a bit harder than the previous request, thus listed separately, but I think/hope it won't need too many changes. 

What do you say?

**Comment by ssb22** [comment]
`O4` and `<` and `>` is taken from SMX code, I did it in [Manuscript Writer](http://ssb22.user.srcf.net/mwrhome/) and you'd be amazed how many times I made the mistake of putting whole sections of music into the wrong octave because I forgot what the current octave is, so when I did jianpu-ly I actually thought "let's not do that again" - I'd rather type `'` or `,` for every note that needs it (yes it's more keystrokes, at least you don't have to look through the whole piece asking "how did we end up in the wrong octave?"

**Comment by suntong** [comment]
Hmm... yeah, you have far more first hand experiences for sure. 

Just like my previous reply, it's not my intention to break any backward compatibility -- the old way still works (and would still be prefered), and this request only provides people with more choices. 

I think the problem eventually bog down to the personal preference, and I can tell that you're strongly prefer against my suggestions, I totally understand it. However, since the author of Alda settled with his personal preference, and he seems to be heavily involved with music composing and note taking, I'd assume that the other way of doing things would be fine too, especially when his approach seems to make things simpler to me. And moreover, correcting the "putting whole sections of music into the wrong octave" problem just need a single change (adding/deleting >/<), whereas otherwise I have to make change to every single note in the whole section. Apparently you think the latter way is simpler, so I think it eventually a problem of personal preference.

Please consider.

**Comment by suntong** [comment]
> I think the problem eventually bog down to the personal preference

I had been thinking why people would have such drastic differences between their preferences, 

> since the author of Alda settled with his personal preference, and he seems to be heavily involved with music composing and note taking, I'd assume that the other way of doing things would be fine too

I now consider that the fact that you are visually challenged make you prefer that every note contain every information it should have, while for people who prefer to look at things as a whole, and have not difficulties scan a big chunk of music notes quickly, they may prefer global optimization as to local optimization. Just a thought and wild guess...

**Comment by ssb22** [comment]
Ah, in the current jianpu-ly version you can't have `>` as a word *by itself*, It has to be part of the same word as a note.

    KeepOctave 2/4 1,, - >1 - >1 - >1 - >1 -

or equivalently,

    KeepOctave 2/4 1,, - 1' - 1' - 1' - 1' -

**Comment by suntong** [comment]
Yep, fixed. thx!

https://github.com/jianpu-ly/jianpu-st/blob/master/demo-octave-smpl.jp
