### ISSUE TITLE
Multiple Voices only in chorus?

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#27]
How to use multiple voices only in chorus? IE, the verse only have single voice yet the chorus has multiple. thx.

**Comment by ssb22** [comment]
well it *will* be something like:

    5 - 6 7 8 - - 7 6 - 7 6 6 5 - -
    H: This is the verse and this is the chorus
    NextPart
    0 0 0 0 0 0 0 5 4 - 5 4 4 3 - -
    H: and this is the chorus

but right now, that results in incorrect output (some of the words get placed under some of the rests), and the reason for that is we're using the wrong `\lyricsTo` parameter.  Lilypond gets a bit "confused" if you have more than one staff with the same name and then you try to attach lyrics that are not always in step.  The answer will be to make sure all the Lilypond staff names are different: I'd better fix that next.

**Comment by suntong** [comment]
:+1: 

![image](https://user-images.githubusercontent.com/422244/231318417-2634af5d-b28c-411a-87e5-2dce56d240b1.png)
