### ISSUE TITLE
Lyric Writer, Composer & Singer

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#28]
How to put Lyric Writer, Composer & Singer onto the sheet?

I tried `arranger=`, but it can only add single line.  
Is there any way to add them in three different lines?

**Comment by ssb22** [comment]
All the available Lilypond headers ([from Lilypond's documentation](https://lilypond.org/doc/v2.22/Documentation/notation/creating-titles-headers-and-footers#default-layout-of-bookpart-and-score-titles)):
* `title`
* `subtitle`
* `subsubtitle`
* `instrument`
* `poet`
* `composer`
* `meter`
* `arranger`
* `tagline`
* `copyright`
* `piece`
* `opus`

So you can use `composer` directly, you can use `poet` for lyric writer, and for singer maybe try `dedication` (goes above the title) or `subtitle` / `subsubtitle` (goes below the title) or `meter` (goes below the lyricist)

**Comment by suntong** [comment]
Thanks!
