### ISSUE TITLE
in some case the %} will comment out some useful code behind it.

### ISSUE THREAD

**Issue by jasongaoks** [ssb22/jianpu-ly#3]
Hi Silas,
in some case the %} will comment out some useful code behind it.
![image](https://user-images.githubusercontent.com/8862093/73965926-fdf29900-494f-11ea-8f3e-c20f3388a3bd.png)
use the jianpu file below will invoke the bug
```
3 - q0 q1 q2 q1
L: aa bb cc dd
```

**Comment by ssb22** [comment]
Oh... that `%}` shouldn't be there at all.  It was added by mistake in v0.158 last May (commit d4bad824df54d36d618bd8e2b3b7972b0ae0e75b) and I'm not sure why it didn't hit my tests!  Fixed in version 3.2 https://github.com/ssb22/jianpu-ly/commit/bc82f55a3af1e7ac055f4772b2d9184882835998

**Comment by jasongaoks** [comment]
Thanks a lot!
