### ISSUE TITLE
One note two words

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#30]
How to put two words into one note please?

**Comment by ssb22** [comment]
Use `L:` mode (so you have to put spaces between each word/syllable) and use `_` instead of space:

    1 - 2 -
    L: this_is_one this_is_two

**Comment by suntong** [comment]
Hmm... can we extend the `_` syntax into `H:` mode please?

If you take a look at [here](https://github.com/jianpu-ly/jianpu-st/blob/master/yydjtz.jp), that's the format I'd like to keep using. thanks.

**Comment by ssb22** [comment]
Please download the latest version: it should work in `H:` mode now, if you use `_` between the characters you want to keep together

**Comment by suntong** [comment]
Works perfectly!! Thanks a lot!

**Comment by suntong** [comment]
Hmm, just noticed that https://github.com/jianpu-ly/jianpu-ly/ was not pushed at the same time, so I synced it for you already, FYI.

**Comment by ssb22** [comment]
Thanks.  I'd done a `git remote set-url origin --push --add` to make it automatic, but I forgot to do the same on the *other* computer I was using....
