### ISSUE TITLE
About chorus

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#32]
Traditional songs have single chorus and many different verses.

How to represent that in [jianpu-ly](https://github.com/ssb22/jianpu-ly) please?

**Comment by ssb22** [comment]
If the chorus comes at the end, you can just make verse 1 longer:

    6, - 7, 1 2 - 1 7, 6, - - 5, 1 - 2 3 4 - 3 2 2 3 - -
    L: this is the mi- nor key verse and this is the ma- jor key chorus
    L: now for verse two we have this
    L: this is the third dem- o verse

**Comment by suntong** [comment]
thanks
