### ISSUE TITLE
"Line" break

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#33]
Is there any way to break the jianpu line at the point that I want?

My jianpu only ends up with two lines, whereas I want it to be 4 lines. thx.

**Comment by ssb22** [comment]
`\break` should do it.  (Any 1-word `\` command is simply passed to Lilypond, so we have access to quite a few Lilypond commands including `\break`)

    1 - 2 3 \break 4 - 3 2 1 - - -

**Comment by suntong** [comment]
Works perfectly!!
