### ISSUE TITLE
Help, how to say this in English

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#34]
Hi @ssb22, sorry to bother you with a simple English question -- 

I want to change a song from F调 to D调.  
How to say it in English pls?

I've gathered and referred to the following,

- https://github.com/jianpu-ly/jianpu-ly/wiki/Ref:-中英文对照版基础乐理知识
- https://github.com/jianpu-ly/jianpu-ly/wiki/Ref:-音乐术语英文名称汇总（一）

_etc_, yet I'm still not sure how to express the idea in English.

So, to change a song from x调 to y调, what are the different ways to express it in English pls? Like,

- This song's 调 is F调.  
- I want to change a song's ??? from F调 to D调.  
- a song was originally sang in F调, I want to change it to a different 调, like D#调,

I'm writing a tool to do that, ref
https://github.com/suntong/ffcvt/issues/30

but I don't know how to write the online help for it. thx.

**Comment by ssb22** [comment]
动词是transpose（变调） and there's a Lilypond command `\transpose` to do it in 五线谱 (jianpu-ly actually uses `\transpose` anyway if you don't use `1=C`)

**Comment by suntong** [comment]
Thanks @ssb22, 

This question actually has nothing to do with jianpu or Lilypond. I'm just using this channel to ask you an irrelevant question -- 

I'm writing a tool to do transpose, and I want do describe such action in English. 

How would you say the following in English please?

- This song's 调 is F调.
- I want to change a song's ??? from F调 to D调.
- a song was originally sang in F调, I want to change it to a different 调, like D#调,

**Comment by suntong** [comment]
NVM. I think I got it. Thanks to your answer of _"动词是transpose（变调）"_
