### ISSUE TITLE
Option to separate midi by instruments

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#38]
Please add an option to [jianpu-ly](https://github.com/ssb22/jianpu-ly) so as to separate midi files by instruments.

Take this [Demo2.jp](https://github.com/jianpu-ly/jianpu-st/blob/master/Demo2.jp) file for example, the generated midi file seems to have two instruments combined into one file, which might be for the most cases, however, it'll be good that we can have separated midi files for different instruments. As we need Soprano / Alto etc to have their own tunes.

Thanks

**Comment by ssb22** [comment]
Lilypond already puts each instrument into a different channel / track, but as it's more convenient just to play the whole MIDI file without loading up some MIDI sequencer software to isolate a channel or track, we can easily get it to generate separate MIDI files as well.

So with the latest version if you put `PartMidi` in the score, you should get `output.midi` for all parts, `output-1.midi` for the first part only, `output-2.midi` for the second part only, etc.  (This numbering will be different if you also have more than one score in the input.)

**Comment by suntong** [comment]
```
MIDI output to `demo-multiple-midis.midi'...
MIDI output to `demo-multiple-midis-1.midi'...
MIDI output to `demo-multiple-midis-2.midi'...
```

Hooray!!! Demo at [demo-multiple-midis.jp](https://github.com/jianpu-ly/jianpu-st/blob/master/demo-multiple-midis.jp).
