### ISSUE TITLE
Repeat broken (my bad)

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#39]
_Originally posted by @ssb22 in https://github.com/ssb22/jianpu-ly/issues/23#issuecomment-1500613842_

> > I also like the idea of the pipe | character, which can be used to represent a bar line separating two measures of music, which can be made optional, and ignored by the compiler, and serve no purpose apart from making the score more readable (and help parsing when note crosses barline cases occurs)

> yes it's doable but ...

When suggesting that ignored pipe | character, I forgot about its usage within repeat. IE now repeat is broken. Please think of ways to fix the situation. The ways I can think of are:

- revert that change and get rid of the ignored pipe | character
- see if possible to use a different character for it (is slash "/" by itself used anywhere?), or
- disable pipe | character within repeat block
- or introduce another directive (say `UseBarLine`) and when given, pipe | character is used to represent a bar line, and the alternate endings syntax changed to slash "/": `R{ 1 1 1 } A{ 2 / 3 }`. (This last option that I just thought of seems to be the best option to me)

Any ways you can think of works for me, as it was my bad introducing the bug. 

Thanks

**Comment by ssb22** [comment]
Well spotted, thanks.  I moved the code around so `|` is an (undocumented) barline check only if we're not in an `A{` block
