### ISSUE TITLE
[Feature] Guitar chords in jianpu-ly

### ISSUE THREAD

**Issue by suntong** [ssb22/jianpu-ly#44]
Similar to #36, this time it is the above note:

![image](https://github.com/ssb22/jianpu-ly/assets/422244/43115b8b-4246-4852-9003-f297e2e4a1ae)

```
| c3 ^"C" - c5 | c2' ^"G7" - - | c1' ^"C" - c5 | c4 ^"F" - -
| c3 ^"C" - c3 |
```

**Comment by ssb22** [comment]
The correct way to do guitar chords in Lilypond is with `\chordmode`:

    LP: << {
    :LP
    c3 - c5 | c2' - - | c1' - c5 | c4 - - | c3 - c3 |
    LP: } \new ChordNames { \chordmode { c2. g7 c f c } } >>
    :LP

Maybe we should do something to make this more automatic.

`^""` is not a good choice for chord names because it's meant for instructions like "faster" and it will put each one at a different height (and also the MIDI output doesn't understand it; doing chord names properly means you get the chords in the midi as well)

**Comment by suntong** [comment]
Wow, that looks ... really ... complicated. 

> Maybe we should do something to make this more automatic.

Yes please think of a better way of authoring it. Otherwise, I think I'll be completely ignoring it as it is just way too difficult to do. Just as a reference, here is how simple to do guitar chords in ABC:

```abc
|: "C"E2G | "G7"d3 | "C"c2G | "F"F3 | "C"E2E | EFG | "Dm"A3 | "G7"G3 |
| "C"E2G | "G7"d3 | "C"c2G | "F"F3 | "C"E2G | "G7"GAB | "C"c3- | c3 ||
||"G7"d z/G/ G | BAG | "C"E2G | c3 | "F"A2c | "D"d2c | "G"B3 | G3 |
| "C"E2G | "G7"d3 | "C"c2G | "F"F3 | "C"E2G | "G7"GAB "C"c3 | c3 :|
```

(Taken from [here](http://trillian.mit.edu/~jc/music/abc/song/Edelweiss_C.abc).)

Also, if possible, design the guitar chords implementation similar to ABC please, i.e., the guitar chords before the note, instead like above note, which follows the music note instead. 

I'll leave this open for you to close.  

Thanks

**Comment by suntong** [comment]
Bravo!

I finally got around to test today, but just realized that I literally know nothing about the Guitar chords. 

So given the above ABC notation of the Guitar chords, how to translate them into jianpu counter-notes pls? What's the rule to transcode from ABC notation of the Guitar chords into jianpu's? thx.

**Comment by suntong** [comment]
NVM, the question should be what's the rule to transcode from ABC notation of the Guitar chords into Lilypond's, and I'll try to find that answer myself...

**Comment by suntong** [comment]
Found one https://github.com/lilypond/lilypond/blob/master/scripts/abc2ly.py, but it's super difficult to figure out the rules for the transcode...

**Comment by ssb22** [comment]
so Lilypond needs to know the duration of each chord: `4` for one beat, `2` for two beats, `2.` for three beats, `1` for four beats.  Default is the same duration as the previous chord, so usually you need to set this up only at the beginning.

For a 7th chord, add `:7` (after the duration, if any).

For a "power chord" add `:5` (I don't think you'll be doing power chords in this sort of music though)

For minor, it's `:m`

For minor 7th, it's `:m7`

Augmented is `:aug` and diminished is `:dim`

Sharp is `is` and flat is `es` (sorry this is all Lilypond code, there's no extra layer of translation right now)

Lilypond also has a function to draw the fingering diagrams for the chords; maybe we should make that an option

**Comment by SilverRainZ** [comment]
wow, I want this function very much, thank you :D

B.T.W. Jianpu usually does not pay much attention to the absolute pitch. Is it possible for us to only label the "level" (I II III IV V VI VII) of the chord rather than the absolute note (A B C D E F G) ?

**Comment by suntong** [comment]
> Jianpu usually does not pay much attention to the absolute pitch. Is it possible for us to only label the "level" (I II III IV V VI VII) of the chord rather than the absolute note (A B C D E F G) ?

I had no idea what the comment meant by then, but having read/watch a lot about it, I think I now know. 
But still, I now also know why chords are done in absolute note, as there's reason behind it. Even the ABC notation is like that, for the same reason I believe.

**Comment by ssb22** [comment]
Chord names as numbers is now being discussed in #55

**Comment by suntong** [comment]
> Guitar chords: `chords=c2. g:7 c` (on own line)

Can you give a sample usage pls Silas?

Use the one I gave in OP as the starting point and also add a case of how to skip a staff pls. 

I'll then try to make the following whole ABC work next.

```
|: "C"E2G | "G7"d3 | "C"c2G | "F"F3 | "C"E2E | EFG | "Dm"A3 | "G7"G3 |
| "C"E2G | "G7"d3 | "C"c2G | "F"F3 | "C"E2G | "G7"GAB | "C"c3- | c3 ||
||"G7"d z/G/ G | BAG | "C"E2G | c3 | "F"A2c | "D"d2c | "G"B3 | G3 |
| "C"E2G | "G7"d3 | "C"c2G | "F"F3 | "C"E2G | "G7"GAB "C"c3 | c3 :|
```

THx!

**Comment by ssb22** [comment]
so I think that ABC would translate to

    chords=c2. g:7 c f c c d:m g:7 c g:7 c f c g:7 c c g:7 g:7 c c f d g g c g:7 c f c g:7 c c
    3/4 R{ 3 - 5 | 9 - - | 8 - 5 | 4 - - | 3 - 3 | 3 4 5 | 6 - - | 5 - - | 3 - 5 | 9 - - | 8 - 5 | 4 - - | 3 - 5 | 5 6 7 | 8 - - | 8 - - | 9 0/ 5/ 5 | 7 6 5 | 3 - 5 | 8 - - | 6 - 8 | 9 - 8 | 7 - - | 7 - - | 3 - 5 | 9 - - | 8 - 5 | 4 | 3 - 5 | 5 6 7 | 8 - - | 8 - - }

If no chord change is indicated in a bar, we should repeat the chord from the previous bar (some music has "N.C." for No Chord, which is written as a rest i.e. `r` in the chords line, but normally the chords just keep going).  We should probably put Lilypond into `chordChanges` mode so it doesn't repeat the chords every bar.

**Comment by ssb22** [comment]
Bar 1 has no chord so you'd put `r` there (rest).  Bar 6 however does *not* have no chord: it has the same chord as bar 5.  When reading a chord line, the assumption is you *continue playing the same chord* until it tells you to *change*.  If they wanted you to *stop* they would write "N.C." (for "no chord")

**Comment by ssb22** [comment]
MuseScore's player also continues holding the chord from bar 5 to bar 6 (they don't sound it a second time, but they don't *stop* the sound either: if you listen carefully, the piano chord from bar 5 is *still sounding* in bar 6).  Many computer players are not very good at playing chord lines as a guitarist would (they'd re-strum it a few times)

**Comment by suntong** [comment]
> MuseScore's player also continues holding the chord from bar 5 to bar 6 (they don't sound it a second time, but they don't stop the sound either...

Ah, yes, indeed. 

![Image](https://github.com/user-attachments/assets/02475d75-d8de-41c6-ab7f-6d9e82138909)

_(I didn't start the free trial so it stops at bar 4, and the one at the very top is bar 6)_

Thanks!!!

**Comment by suntong** [comment]
Why the first chord is `c2.` Silas? I can understand all the rest but not this first one.

Also, I found that the bar number placing is inconsistent:

![Image](https://github.com/user-attachments/assets/1cb9404a-b39d-4d68-92c0-f44a99538fab)

It's not a big deal, but if you could fix it, that's be good. thx.

**Comment by ssb22** [comment]
The `2.` is to set the duration of chords: in this case we want the chord to be the length of a dotted minim, which is the length of a bar.

The placement of bar numbers is done by Lilypond, not us.  The reason why it's inconsistent is because of Lilypond's skyline algorithm: a single-digit bar number like "5" can fit in nice and close to the barline, but once this becomes double digits like "20" it can no longer fit there, so Lilypond puts it higher up instead.

You could try:

    LP: \override Score.BarNumber.self-alignment-X = #CENTER
    :LP

which might work around the problem for this *particular* piece (chord changes at the start of bars)

**Comment by suntong** [comment]
Thanks Silas.

> The 2. is to set the duration of chords: in this case we want the chord to be the length of a dotted minim, which is the length of a bar.

So, 

- for `3/4` beat, use `2.` after the first chord, meaning a dotted minim.
- for `2/4` beat, use `2` after the first chord?
- for `4/4` beat, use `4` after the first chord?

Thanks

**Comment by ssb22** [comment]
Not quite.

**If a chord lasts a whole bar** then it's `2` for 2/4, `2.` for 3/4 and `1` for 4/4.  (`4` would be for 1/4, `8` for 1/8 etc.)

But in some music, the chord changes in the middle of the bar.  We cannot always assume it will last a bar.  That's why we have to set it.
