### ISSUE TITLE
Fine at repeat start

### ISSUE THREAD

**Issue by 837951602** [ssb22/jianpu-ly#56]
2/4 1 1 Fine R{ 1 1 } 1 1 DC

Expected 
![图片](https://github.com/user-attachments/assets/c10263c7-007d-4655-bfe7-7c966ce10b3f)

Got
![图片](https://github.com/user-attachments/assets/f4230292-462e-4e81-9f17-94b7a87984e0)

**Comment by ssb22** [comment]
that's because `Fine` makes us send a `\bar "|."` to Lilypond (to get the normal double bar at the Fine), and this overrides the default "repeat" barline type.  Need to detect if a repeat starts immediately afterwards and suppress the `\bar "|."`
