### ISSUE TITLE
Can this script adjust width and height for lines?

### ISSUE THREAD

**Issue by TatenLee** [ssb22/jianpu-ly#67]
Hi @ssb22:
    Very appreciate for share this tool, it's realy convinient for every musician to generate jianpu.
    But when I use this scipt, I found a problem that it's very tight between two pitches. How can I adjust numbers of sections of lines, and width between sections?
    The other problem I met is how can I put a new font that I created in this output? I created some jianzi(Chinese guqin symbols) mapping pitches, but it is not known by general system.
    Hope for your reply, thanks!

**Comment by unbored** [comment]
If the first problem is to help solving the second one, I would suggest my forked project generating jianzi automatically. Here is the link: 
https://github.com/unbored/jianpu-ly/tree/Guqin
And the related project JianziNote:
https://github.com/unbored/JianziNote

**Comment by ssb22** [comment]
多谢@unbored!  恐怕我不太了解@TatenLee的要求但看起来你已经熟悉∼

**Comment by ssb22** [comment]
I just realised "sections of lines" might be a mistranslation of 小节线 (bar lines), so this is asking about bar numbering and barline width?  Or perhaps it's something else and I still haven't understood it.  Anyway I hope @unbored's fork is a good starting point!

**Comment by unbored** [comment]
I suppose @TatenLee means to extend the interval s between the numbers so that a relatively large character can be put under each of the numbers, which looks like lyrics with very large font size, as what a normal Guqin score will do. I happened to join this project right for that.

**Comment by TatenLee** [comment]
@ssb22 haha, sorry for my ambiguous description, you are right. I mistranslate bar lines. I wanna extend the distance between two bar lines. @unbored understood my description
